config/routes.rb
Kandan::Application.routes.draw do

  devise_for :users,
  :controllers => {
    :sessions => "sessions"
  }

  get "pages/approval"

  get "pages/suspended"

  root :to => "main#index"
  devise_for :users

  get '/search' => "main#search"

  resources :channels do
    resources :activities
    resources :attachments
  end

  resources :users, :only => [:index, :show]

  get "/active_users" => "apis#active_users"
  get "/me" => "apis#me"
 
  get "/users/edit" =>"main#users_edit"

  namespace :admin do
    root :to => "admin#index"
    post "/update", :to => "admin#update", :as => "update"
    post "/update_user", :to => "admin#update_user", :as => "update_user"
    post "/toggle_admin", :to => "admin#toggle_admin"
  end

  get "/approval", :to => "pages#approval"
  get "/suspended", :to => "pages#suspended"
  get "/about", :to =>"pages#about"

end

app/views/admin/admin/_user_table.html.erb
<% show_admin_column = defined?(show_admin) && show_admin ? true : false%>
<table <%= inline_style_hidden(users.empty?)%> class="table table-striped table-bordered" cellspacing="0" cellpadding="0" border="0">
	<thead>
		<tr>
			<th class="username">Username</th>
			<th class="first_name">First Name</th>
			<th class="last_name">Last Name</th>
			<th class="email">Email</th>
			<th class="statu">Status</th>
			<th class="action">Action</th>
			<th class="admin" <%= inline_style_hidden( !show_admin_column ) %> >Admin</th>
		</tr>
	</thead>
	<tbody>
		<% users.each do |user| %>
			<tr class="<%= cycle('odd', 'even')%>" data-user-id="<%= user.id%>" data-full-name="<%= user.full_name_or_username %>">
				<td class="username">
					<%= user.username %>
				</td>
				<td class="first_name">
					<%= user.first_name %>
				</td>
				<td class="last_name">
					<%= user.last_name %>
				</td>
				<td class="email">
					<%= user.email %>
				</td>
				<td class="status">
					<%= user_registration_status(user) %>
				</td>
				<td class="action">
					<%= user_action(user) %>
				</td>
				<td class="admin" <%= inline_style_hidden( !show_admin_column ) %>>
					<input type="checkbox" <%=  "checked" if user.is_admin? %> />
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<div class="js-no-users" <%= inline_style_hidden(users.any?)%> >There are no users. Invite others to join Kandan!</div>

app/views/admin/admin/index.html.erb
<% content_for :javascript_includes do %>
	<%= javascript_include_tag "admin/admin" %>

	<%# Removed the following line when we start using Bootstrap all over the app %>
	<%= stylesheet_link_tag  "admin", :media => "all" %>
<% end %>

<div class="container">
	<div class="admin-main-area span12">
		<h3>Site settings</h3>
		<%= form_for @settings, :url => admin_update_path, :method => :post, :html => { :class => "" } do |f| %>
		  <div class="control-group">
		  	<%= f.label :max_rooms, 'Max number of rooms', :class => "control-label" %>
		  	<div class="controls">
		  		<%= f.number_field :max_rooms, :class => "input-mini" %>
		  	</div>
		  </div>
		  <div class="control-group">
		  	<%= f.label :public_site, 'Is this a public site?', :class => "control-label" %>
		  	<div class="controls">
		  		<%= f.check_box :public_site %>
		  	</div>
		  </div>
		  <div class="control-group">
		  	<%= f.submit :class => "btn btn-success" %>
		  </div>
		<% end %>

		<div class="waiting-for-approval-users">
			<h3>Users waiting for approval</h3>
			<%= render "user_table", :users => @waiting_for_approval_users %>
		</div>

		<div class="approved-users">
			<h3>All users</h3>
			<%= render "user_table", :users => @approved_users, :show_admin => true %>
		</div>
	</div>
</div>