config/routes.rb
Kandan::Application.routes.draw do

  devise_for :users,
  :controllers => {
    :sessions => "sessions"
  }

  get "pages/approval"

  get "pages/suspended"

  root :to => "main#index"
  devise_for :users

  get '/search' => "main#search"

  resources :channels do
    resources :activities
    resources :attachments
  end

  resources :users, :only => [:index, :show]

  get "/active_users" => "apis#active_users"
  get "/me" => "apis#me"
 
  get "/users/edit" =>"main#users_edit"

  namespace :admin do
    root :to => "admin#index"
    post "/update", :to => "admin#update", :as => "update"
    post "/update_user", :to => "admin#update_user", :as => "update_user"
    post "/toggle_admin", :to => "admin#toggle_admin"
  end

  get "/approval", :to => "pages#approval"
  get "/suspended", :to => "pages#suspended"
  get "/about", :to =>"pages#about"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kandan</title>
  <%= stylesheet_link_tag  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/ui-lightness/jquery-ui.css" %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=PT+Sans:400,700" %>
  <%= stylesheet_link_tag  "application", :media => "all" %>
  <%= favicon_link_tag %>
  <%= javascript_include_tag "application" %>
  <%= yield :javascript_includes %>

  <%= csrf_meta_tags %>

  <%- if user_signed_in? %>
    <%= javascript_tag do %>
      $.data(document, "current-user", <%= current_user_data.to_json.html_safe %>);
    <% end %>
  <%- end %>
</head>
<body data-kandan-config="<%= Kandan::Config.to_json %>">
  <div id="kandan">
    <div class="header">
      <a href="/">
        <%= image_tag "logo.png", :class=>"logo" %>  
      </a>
      <% if user_signed_in? %>
        <a href="#" class="user_menu_link">
          <cite class="user_flag"></cite>
          <div class="user">
            <img src="<%= avatar_url_for(current_user, :size => 25) %>"/>
            <span><%= current_user.full_name_or_username %></span>
          </div>
        </a>
        <%= yield :header_content %>
      </div>
      <div class="user_menu">
        <%= link_to 'Admin console', admin_root_path, :target => "_blank" if current_user.is_admin? %>
        <%= link_to 'Edit Account', users_edit_path, :target => "_blank" %><br />
        <%= link_to 'Logout', destroy_user_session_path, :method => :delete %><br />
        <hr>
        <%= link_to 'About Kandan', about_path, :target => "_blank" %>
      </div>
    <% else %>
      </div>
      <% end %>
    <div id="app_body">

    <%= yield %>

    </div>
  </div>
</body>
</html>